# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('number', models.IntegerField()),
                ('percent_white', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percent_black', models.DecimalField(decimal_places=2, max_digits=4)),
                ('percent_hispanic', models.DecimalField(decimal_places=2, max_digits=4)),
                ('occupied_housing', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('tract', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
                ('tax_debt', models.FloatField()),
                ('property_value', models.IntegerField()),
                ('property_class_code', models.CharField(max_length=50)),
                ('owner_address', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.BooleanField()),
                ('highest_sales_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('finished_sq_feet', models.PositiveSmallIntegerField()),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('constructed_year', models.PositiveSmallIntegerField()),
                ('census_tract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.CensusTract')),
            ],
        ),
    ]
