# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20171118_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censustract',
            name='percent_hispanic',
        ),
        migrations.AddField(
            model_name='property',
            name='property_pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
