# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20171118_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censustract',
            name='occupied_housing',
        ),
    ]
