# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_censustract_occupied_housing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tax_debt',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tract',
        ),
        migrations.AlterField(
            model_name='property',
            name='census_tract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.CensusTract'),
        ),
    ]
