# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20171118_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
