# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20171119_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='acreage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
